name: NArtefacts
version: '${project.version}'
main: ru.noquery.www.nartefacts.NArtefacts
api-version: '1.20'
author: 'Noquery'

commands:
  arthassword:
    description: ""
    usage: "/arthassword"
    aliases: [asword]
    permission: permission.arthassword
    permission-message: "You do not have permission to use this command"
